// <auto-generated />
using FaraTaraz.Modules.AccountingSources.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FaraTaraz.Modules.AccountingSources.Infrastructure.Migrations
{
    [DbContext(typeof(AccountingSourcesDbContext))]
    [Migration("20261009180140_FTW2-InitialSchema")]
    partial class FTW2InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FaraTaraz.Modules.AccountingSources.Infrastructure.Persistence.AccountingSourceEntity", b =>
                {
                    b.Property<string>("TenantId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("TenantId", "Id");

                    b.HasIndex("TenantId", "Id")
                        .IsUnique()
                        .HasDatabaseName("UQ_AccountingSources_Tenant_Id");

                    b.ToTable("AccountingSources", (string)null);
                });

            modelBuilder.Entity("FaraTaraz.Modules.AccountingSources.Infrastructure.Persistence.TenantEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("Tenants", (string)null);
                });

            modelBuilder.Entity("FaraTaraz.Modules.AccountingSources.Infrastructure.Persistence.AccountingSourceEntity", b =>
                {
                    b.HasOne("FaraTaraz.Modules.AccountingSources.Infrastructure.Persistence.TenantEntity", "Tenant")
                        .WithMany("AccountingSources")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("FaraTaraz.Modules.AccountingSources.Infrastructure.Persistence.TenantEntity", b =>
                {
                    b.Navigation("AccountingSources");
                });
#pragma warning restore 612, 618
        }
    }
}
