<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\BuildingBlocks\FaraTaraz.BuildingBlocks.csproj" />
    <ProjectReference Include="..\..\Modules\MasterData\FaraTaraz.Modules.MasterData.csproj" />
    <ProjectReference Include="..\..\Modules\Ingestion\Ingestion.Domain\FaraTaraz.Modules.Ingestion.Domain.csproj" />
    <ProjectReference Include="..\..\Modules\AccountingSources\FaraTaraz.Modules.AccountingSources.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="FaraTaraz.Modules.AccountingSources.Providers" />
    <Using Include="FaraTaraz.Modules.AccountingSources.Capabilities" />
    <Using Include="FaraTaraz.Modules.AccountingSources.Authorization" />
  </ItemGroup>
</Project>
