<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\FaraTaraz.BuildingBlocks.csproj" />
    <ProjectReference Include="..\Ingestion.Domain\FaraTaraz.Modules.Ingestion.Domain.csproj" />
    <ProjectReference Include="..\..\AccountingSources\FaraTaraz.Modules.AccountingSources.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="12.5.0" />
    <PackageReference Include="MediatR.Contracts" Version="2.0.1" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="FaraTaraz.Modules.AccountingSources.Providers" />
    <Using Include="FaraTaraz.Modules.AccountingSources.Capabilities" />
    <Using Include="FaraTaraz.Modules.AccountingSources.Authorization" />
  </ItemGroup>
</Project>
