<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <EnableMigrate>true</EnableMigrate>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\BuildingBlocks\FaraTaraz.BuildingBlocks.csproj" />
    <ProjectReference Include="..\..\src\Modules\AccountingSources\FaraTaraz.Modules.AccountingSources.csproj" />
    <ProjectReference Include="..\..\src\Modules\AccountingSources\AccountingSources.Infrastructure\FaraTaraz.Modules.AccountingSources.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Modules\Ingestion\Ingestion.Domain\FaraTaraz.Modules.Ingestion.Domain.csproj" />
    <ProjectReference Include="..\..\src\Modules\Ingestion\Ingestion.Infrastructure\FaraTaraz.Modules.Ingestion.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
