namespace FaraTaraz.ArchitectureTests;

using System;
using System.IO;
using System.Linq;
using Xunit;

/// <summary>Repository-wide source file size budget. No silent per-file exceptions.</summary>
public sealed class SourceFileSizeGuardTests
{
    private const int ProductionMaxLines = 300;
    private const int TestMaxLines = 500;
    private const int ReviewThreshold = 250;

    private static string FindRepoRoot()
    {
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir is not null)
        {
            if (File.Exists(Path.Combine(dir.FullName, "FaraTaraz.sln")))
                return dir.FullName;
            dir = dir.Parent;
        }
        throw new FileNotFoundException("Repository root (FaraTaraz.sln) not found.");
    }

    [Fact]
    public void Production_and_test_source_files_stay_within_budgets()
    {
        var root = FindRepoRoot();
        var failures = new System.Collections.Generic.List<string>();
        foreach (var (folder, limit) in new[] { ("src", ProductionMaxLines), ("tests", TestMaxLines) })
        {
            var basePath = Path.Combine(root, folder);
            foreach (var file in Directory.EnumerateFiles(basePath, "*.cs", SearchOption.AllDirectories))
            {
                var relative = Path.GetRelativePath(root, file).Replace('\\', '/');
                if (relative.Split('/').Any(s => s is "obj" or "bin"))
                    continue;
                // Generated C# is excluded only when explicitly marked by a generated-code header.
                var lines = File.ReadAllLines(file);
                if (lines.Take(10).Any(s => s.Contains("<auto-generated", StringComparison.OrdinalIgnoreCase)))
                    continue;
                if (lines.Length > limit)
                    failures.Add($"{relative}: {lines.Length} lines exceeds {limit}");
            }
        }
        Assert.True(failures.Count == 0, "Source file size violations:" + Environment.NewLine
            + string.Join(Environment.NewLine, failures.OrderBy(x => x, StringComparer.Ordinal)));
    }

    [Fact]
    public void Review_threshold_is_below_production_hard_limit()
        => Assert.True(ReviewThreshold < ProductionMaxLines);
}
