namespace FaraTaraz.ArchitectureTests;

using System;
using System.IO;
using System.Linq;
using Xunit;

/// <summary>Repository-wide source file size budget. No silent per-file exceptions.</summary>
public sealed class SourceFileSizeGuardTests
{
    private const int ProductionMaxLines = 300;
    private const int TestMaxLines = 500;
    private const int ReviewThreshold = 250;

    private static string FindRepoRoot()
    {
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir is not null)
        {
            if (File.Exists(Path.Combine(dir.FullName, "FaraTaraz.sln")))
                return dir.FullName;
            dir = dir.Parent;
        }
        throw new FileNotFoundException("Repository root (FaraTaraz.sln) not found.");
    }

    [Fact]
    public void Production_and_test_source_files_stay_within_budgets()
    {
        var root = FindRepoRoot();
        var failures = new System.Collections.Generic.List<string>();
        foreach (var (folder, limit) in new[] { ("src", ProductionMaxLines), ("tests", TestMaxLines) })
        {
            failures.AddRange(EnumerateBudgetViolations(root, folder, limit));
        }

        Assert.True(failures.Count == 0, "Source file size violations:" + Environment.NewLine
            + string.Join(Environment.NewLine, failures.OrderBy(x => x, StringComparer.Ordinal)));
    }

    /// <summary>
    /// Regression: a production file that exceeds the line budget is detected by the scan.
    /// A passing guard must actually catch an oversized file, not merely report the repo.
    /// </summary>
    [Fact]
    public void Oversized_source_file_is_detected()
    {
        var root = Path.Combine(Path.GetTempPath(), "ft-size-guard", Guid.NewGuid().ToString("N"));
        var src = Path.Combine(root, "src");
        Directory.CreateDirectory(src);

        var lines = new string[ProductionMaxLines + 1];
        for (var i = 0; i < lines.Length; i++)
        {
            lines[i] = "// line " + i;
        }

        File.WriteAllText(Path.Combine(src, "Oversized.cs"), string.Join(Environment.NewLine, lines));

        try
        {
            var violations = EnumerateBudgetViolations(root, "src", ProductionMaxLines);
            Assert.Contains(violations, v => v.Contains("Oversized.cs"));
        }
        finally
        {
            Directory.Delete(root, true);
        }
    }

    /// <summary>
    /// Scans <paramref name="folder"/> under <paramref name="root"/> for production/test source
    /// files that exceed <paramref name="limit"/> lines. Generated C# (an explicit
    /// <c>&lt;auto-generated&gt;</c> header in the first ten lines) is excluded. Extracted so the
    /// budget rule can be exercised against a controlled fixture, not just the live repo.
    /// </summary>
    private static System.Collections.Generic.IEnumerable<string> EnumerateBudgetViolations(
        string root, string folder, int limit)
    {
        var basePath = Path.Combine(root, folder);
        foreach (var file in Directory.EnumerateFiles(basePath, "*.cs", SearchOption.AllDirectories))
        {
            var relative = Path.GetRelativePath(root, file).Replace('\\', '/');
            if (relative.Split('/').Any(s => s is "obj" or "bin"))
                continue;

            var lines = File.ReadAllLines(file);
            if (lines.Take(10).Any(s => s.Contains("<auto-generated", StringComparison.OrdinalIgnoreCase)))
                continue;

            if (lines.Length > limit)
                yield return $"{relative}: {lines.Length} lines exceeds {limit}";
        }
    }

    [Fact]
    public void Review_threshold_is_below_production_hard_limit()
        => Assert.True(ReviewThreshold < ProductionMaxLines);
}
